# Generated by Django 5.1.3 on 2024-12-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_friendinvitation_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user2',
        ),
        migrations.DeleteModel(
            name='FriendInvitation',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
