# Generated by Django 5.1.3 on 2025-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
