name: Python application

on:
  push:
    branches: [ "main", "be_develop", "fe_develop" ]
  pull_request:
    branches: [ "main", "be_develop", "fe_develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: private_chat_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-django
        if [ -f Backend/requirements.txt ]; then pip install -r Backend/requirements.txt; fi
        
    - name: set env variable for pytest
      run: echo "DJANGO_SETTINGS_MODULE=backend.settings" >> $GITHUB_ENV
      
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      
    - name: Test with pytest
      working-directory: ./Backend
      env:
        DB_USER: postgres
        DB_PASSWORD: postgres
      run: |
        python manage.py migrate
        pytest
